# [Changed] Print Width, Default: 80
printWidth: 120
# Tab Width, Default: 2
tabWidth: 2
# Tabs, Default: false
useTabs: false
# [Changed] Semicolons, Default: true
semi: false
# [Changed] Quotes, Default: false
singleQuote: true
# [Changed] Quote Props, Valid options: "as-needed" "consistent" "preserve", Default: "as-needed"
quoteProps: 'consistent'
# JSX Quotes, Default: false
jsxSingleQuote: false
# Trailing Commas, Valid options: "all" "es5" "none", Default: "all"
trailingComma: 'all'
# Bracket Spacing, Default: true
bracketSpacing: true
# Object Wrap, Valid options: "preserve" "collapse", Default: "preserve"
objectWrap: 'preserve'
# [Changed] Bracket Line, Default: false
bracketSameLine: true
# Arrow Function Parentheses, Valid options: "always" "avoid", Default: "always"
arrowParens: 'always'
# Require Pragma, Default: false
requirePragma: false
# Insert Pragma, Default: false
insertPragma: false
# Check Ignore Pragma, Default: false
checkIgnorePragma: false
# Prose Wrap, Valid options: "always" "never" "preserve", Default: "preserve"
proseWrap: 'preserve'
# HTML Whitespace Sensitivity, Valid options: "css" "strict" "ignore", Default: "css"
htmlWhitespaceSensitivity: 'css'
# Vue files script and style tags indentation, Default: false
vueIndentScriptAndStyle: false
# Vue files script and style tags indentation, Valid options: "lf" "crlf" "cr" "auto", Default: "lf"
endOfLine: 'lf'
# Embedded Language Formatting, Valid options: "auto" "off", Default: "auto"
embeddedLanguageFormatting: 'auto'
# Single Attribute Per Line, Default: false
singleAttributePerLine: false
