# Project information
site_name: Vibyird的笔记
site_url: https://notes.medowo.net
site_author: Vibyird
site_description: Vibyird写的博客和归纳整理的知识笔记

# Copyright
copyright: Copyright &copy; 2025 Vibyird

# Navigation
nav:
  - 主页:
      - blog/index.md
  - 容器:
      - container/index.md
      - Docker:
          - container/docker/index.md
      - Containerd:
          - container/containerd/get-started.md
          - container/containerd/rootless.md
          - container/containerd/build.md
  - 网络:
      - network/index.md

# Configuration
theme:
  language: zh
  custom_dir: overrides
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    # - search.highlight
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: lucide/sun-moon
        name: 系统默认
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: lucide/sun
        name: 浅色模式
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: lucide/moon
        name: 深色模式

# Plugins
plugins:
  - blog:
      post_url_format: '{date}/{file}'
  - meta
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      js_files:
        - assets/javascripts/extra.js
      minify_inline_js: true
      minify_inline_css: true

# Additional configuration
extra:
  homepage: /blog/
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vibyird

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.admonition
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format

extra_javascript:
  - assets/javascripts/extra.js
