# Project information
site_name: Vibyird的笔记
site_url: https://www.medowo.net

# Copyright
copyright: Copyright &copy; 2025 Vibyird

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
  # - announce.dismiss
  # - content.action.edit
  # - content.action.view
  # - content.code.annotate
  # - content.code.copy
  # - content.code.select
  # - content.footnote.tooltips
  # - content.tabs.link
  # - content.tooltips
  # - header.autohide
  # - navigation.expand
  # - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  # - navigation.prune
  - navigation.sections
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.top
  # - navigation.tracking
  # - search.highlight
  # - search.share
  # - search.suggest
  - toc.follow
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-6
      name: 系统默认
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/brightness-7
      name: 浅色模式
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/brightness-4
      name: 深色模式

# Plugins
plugins:
- meta
- search
- blog
- git-revision-date-localized:
    type: date
    timezone: Asia/Shanghai
    locale: zh_CN
    enable_creation_date: false
    exclude:
    - index.md
    - blog/*

# Additional configuration
extra:
  homepage: /blog/
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vibyird

# Extensions
markdown_extensions:
- meta
- attr_list
- md_in_html
- pymdownx.blocks.caption

# Page tree
nav:
- 主页: 
  - blog/index.md
- 容器: 
  - container/index.md
  - container/containerd.md
- 网络: 
  - network/index.md
